### Spring properties
# Service registers under this name
spring:
  application:
    name: users-microservice
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
    ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3308/SpringMs
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: SELECT 1 FROM users
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 4444

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false